### PR TITLE
Add mongo configuration, fixes #40

### LINKED ISSUE #40: Database configuration
Hi,

I have just downloaded malcom to test it but I am unable to launch it simply because: 
1. my database is on another computer than the one I want to run malcom on
2. I have configured authentication on my MongoDB

I see you have created a *db_local* section in the _malcom.conf_ file but, as my comprehension of the code goes, it does not seem to be used when creating the database sessions (at least in the ```Model``` and ```UserManagement``` classes)

Are you working on it (since the *db_local* section exists) or would you prefer a pull request?

### PR DESCRIPTION
**Pull request by srilumpa**
Hi,

This should do the work to fix #40. I wasn't able to test all the cases (mainly the replicaset part) but I was able to change the database, connect to a remote mongo instance and authenticate against the database.

I'm quite new to python so I'm not sure that the 
```python
from __main__ import setup
```
is the right way to propagate the configuration. I figured it was the easiest way allowing reading the configuration without having to refactor a lot more of code.

I also updated the `malcom.conf.exemple` and the `README.md` files accordingly to the changes.

### CODE REVIEW

**Comment by tomchop** [comment]
The ideal would be to pass all configuration / settings parameters to the constructors of the various classes. I think something along [these lines](http://stackoverflow.com/questions/24023601/is-it-good-practice-to-use-import-main) would be more appropriate.

That said, you'd have to change the constructors for `Analytics`,`Web`, and `Feeds`. Feel free to code it up if you feel up to the challenge :) If not, I'll just keep working on this PR and merge when I'm done. Thanks!

**Comment by srilumpa** [comment]
That's what I thought. I tried at first to propagate configuration through the constructors. The ```Feeds``` class was quite easy but the ```Analytics``` and ```Web``` ones not so much.

I'll try to find the proper way to initiate the ```Model``` and ```UserManagement``` classes and I'll update the PR.

**Comment by srilumpa** [comment]
I removed the ```__main__``` import to pass the configuration to each constructor instead. For the webserver part, I used a decorator as suggested in the [Flask documentation](http://flask.pocoo.org/docs/0.10/tutorial/dbcon/#tutorial-dbcon).

Everything seems to run correctly : refreshing feeds from the WUI, displaying nodes, inserting dataset... I didn't test the API nor the Netsniffer though.

**Comment by tomchop** [comment]
Merged with a few extra changes. Thanks for all the work!

**Pull request merged**
