### PR TITLE
correct malcode feed

### PR DESCRIPTION
**Pull request by sebdraven**

### CODE REVIEW

**Comment by sebdraven** [comment]
Rebuild API with RestFull

**Comment by tomchop** [comment]
When browsing on `/dataset`, I get the following error:
```
Traceback (most recent call last):
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/geventwebsocket/handler.py", line 88, in run_application
    return super(WebSocketHandler, self).run_application()
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 494, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/home/malcom/malcom/Malcom/web/webserver.py", line 646, in malcom_app
    return app(environ, start_response)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask_login.py", line 755, in decorated_view
    return func(*args, **kwargs)
  File "/home/malcom/malcom/Malcom/web/webserver.py", line 451, in dataset
    return render_template("dataset.html")
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/malcom/malcom/Malcom/web/templates/dataset.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/malcom/malcom/Malcom/web/templates/base.html", line 115, in top-level template code
    {% block sidebar %}
  File "/home/malcom/malcom/Malcom/web/templates/dataset.html", line 39, in block "sidebar"
    <input id="query" class="form-control input-sm" data-url="{{ url_for('malcom_api.query_data') }}" placeholder='tags=evil'>
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/helpers.py", line 305, in url_for
    force_external=external)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1649, in build
    raise BuildError(endpoint, values, method)
BuildError: ('malcom_api.query_data', {}, None)
```

**Comment by tomchop** [comment]
When doing a get request for `http://malcom:8080/api/neighbors/?_id=54f769101d41c8040c7a9543` (`space` key on the graph)

```
Traceback (most recent call last):
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/geventwebsocket/handler.py", line 88, in run_application
    return super(WebSocketHandler, self).run_application()
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 494, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/home/malcom/malcom/Malcom/web/webserver.py", line 646, in malcom_app
    return app(environ, start_response)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 262, in error_router
    return self.handle_error(e)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 262, in error_router
    return self.handle_error(e)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 446, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 550, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/malcom/malcom/Malcom/web/api.py", line 80, in get
    query[key] = {"$in" : [ObjectId(id) for id in request.args.get(key)]}
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/bson/objectid.py", line 121, in __init__
    self.__validate(oid)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/bson/objectid.py", line 228, in __validate
    _raise_invalid_id(oid)
  File "/home/malcom/env-malcom/local/lib/python2.7/site-packages/bson/objectid.py", line 61, in _raise_invalid_id
    oid, binary_type.__name__))
InvalidId: u'5' is not a valid ObjectId, it must be a 12-byte input of type 'str' or a 24-character hex string
```

**Comment by tomchop** [comment]
Merged in de7b2c2cee14fbdf2dfbcfa7476943334443ea18

**Pull request closed without merging**
